swagger: "2.0"
info:
  description: "Communication method to understand the JSON output produced by the Angle Model and Blur models. <br /><br /> This is however not API documentation."
  version: "1.0.0"
  title: "Angle and Blur JSON documentation"
paths:
  /angle/coverage:
    post:
      tags:
      - "angle"
      summary: "JSON documentation for angle response."
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/coverage"
  /quality/blur:
    post:
      tags:
      - "quality"
      summary: "JSON documentation for blur response."
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/blur"
definitions:
  quadrants:
    type: "object"
    properties:
      first_quad:
        type: "array"
        items: 
          type: "string"
      second_quad:
        type: "array"
        items: 
          type: "string"
      third_quad:
        type: "array"
        items: 
          type: "string"
      fourth_quad:
        type: "array"
        items: 
          type: "string"
  coverage:
    type: "object"
    required: 
      - pole_name
      - total_images
    properties:
      pole_name:
        type: "string"
        description: "Pole name taken from parsing the image name."
      total_images:
        type: "integer"
        description: "The number of images for the structure."
      total_angle:
        type: "number"
        description: "Total angles covered by the images out of 360 degrees. This excludes low altitude images if it applies."
      mean_angle:
        type: "number"
        description: "The average angle of each image. This excludes low altitude images if it applies."
      low_altitude_excluded:
        type: "array"
        items: 
          type: "string"
        description: "Name of the images that are significantly lower than the rest of the images evaluated. Image is excluded from overall calculations."
      error:
        type: string
        enum:
          - "At least one missing quadrant."
      quadrants:
        $ref: "#/definitions/quadrants"
      top_view_image:
        type: "string"
        description: "Name of the image that is closest to the centroid as defined by the model."
  blur:
    type: "object"
    required: 
      - pole_name
      - total_images
    properties:
      pole_name:
        type: "string"
        description: "Pole name taken from parsing the image name."
      total_images:
        type: "integer"
        description: "The number of images processed for the structure."
      images:
        $ref: "#/definitions/images"
  images:
    type: "object"
    required: 
      - image_name
      - model_status
    properties:
      image_name:
        type: string
        description: "Name of the image."
      model_status:
        type: string
        enum:
          - "Successfully processed"
          - "Unable to detect object."
        description: "Status on if the model was able to run blur detection or not."
      blur_percentage:
        type: number
        description: "The image is first cropped to the area of interest. The percent represented here is the percent blur on the cropped image."
      cropped_output:
        type: string
        description: "The name (maybe location?) of the cropped image so we can validate if the blur_percentage number does not seem right."
    
